apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-demo
  namespace: sre-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-demo
  template:
    metadata:
      labels:
        app: crashloop-demo
    spec:
      containers:
        - name: crash
          image: busybox:1.36
          command: ["/bin/sh", "-c", "echo 'crashloop demo'; sleep 2; exit 1"]
